name: Self Hosted

on:
  # I not want build every push and pull requests. (for now) - mcagabe19
  # push:
    # branches: [ main ]
  # pull_request:
    # branches: [ main ]
  workflow_dispatch:

jobs:
  Android:
    permissions: write-all
    name: Android
    runs-on: Lilian
    steps:
       - name: Switch Haxelibs
         run: taskset -a -c 3-7 haxelib setup $TERMUX_HOME/haxelibpsych && taskset -a -c 3-7 haxelib set openfl 9.2.1
       - name: Fetch Upstream
         run: cd ~/repos/FNF-PsychEngine-Mobile && taskset -a -c 3-7 git pull
       - name: Toaster (Build Started)
         run: taskset -a -c 3-7 termux-toast "A Build has been started"
       - name: Compile
         run: cd ~/repos/FNF-PsychEngine-Mobile && taskset -a -c 4-7 lime build android -armv7 -D officialBuild -D NO_PRECOMPILED_HEADERS -D mobileC -release && mv export/release/android/bin/app/build/outputs/apk/release/*.apk /sdcard/Download/builds/psych
         env:
          cert_pass: nullfunni
          cert_alias_pass: nullfunni
       - name: Toaster (Fail)
         if: failure()
         run: taskset -a -c 3-7 termux-toast "Build Failed"
       - name: Toaster (Success)
         if: success()
         run: taskset -a -c 3-7 termux-toast "Build Success"
       - name: Toaster (Cancel)
         if: cancelled()
         run: termux-toast "Build Cancelled"
       # - name: Delete Useless
         # run: cd ~/GitHub/repos/FNF-PsychEngine-Mobile && rm -rfv export/release/android/bin && rm -rfv export/release/android/obj/*.so*
       # - name: Publish Artifact
         # uses: actions/upload-artifact@main
         # with:
           # name: buildAndroid-release
           # path: '/sdcard/Download/builds/psych/*.apk'
           # if-no-files-found: error
